name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup
      run: brew install boost capnp google-sparsehash multimarkdown ninja ragel
    - name: Configure
      run: ./configure
    - name: Build
      run: ninja TextMate
